title: Superinis blogas
author: Rasa
email: rasa.z@datadog.org
description: > # this means to ignore newlines until "baseurl:"
  Puikus aprašymas

# social links
twitter_username: your-twitter-handle
github_username:  rasa05

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
